### ISSUE TITLE
ItemBuilder#onInteract doesn't work

### ISSUE THREAD

**Issue by noaottermann** [Sunderia/SunderiaUtils#3]
Check my project here : https://github.com/Sunderia/SunderiaSkyBlock
In the Items enum there is a "3X3Pickaxe" with an onInteract that's supposed to print "test" but when i interact with my pickaxe in my
Minecraft server it doesn't print "test"

**Comment by Minemobs** [comment]
yes

**Comment by noaottermann** [comment]
no

**Comment by noaottermann** [comment]
please help

**Comment by Minemobs** [comment]
Fixed.
