### ISSUE TITLE
event.setCancelled(true) with ItemBuilder#onInteract doesn't work

### ISSUE THREAD

**Issue by noaottermann** [Sunderia/SunderiaUtils#7]
Items with cancelled true are not cancelled

**Comment by Minemobs** [comment]
Can you post your code ?

**Comment by noaottermann** [comment]
inventory.setItem(index, cancelled ? new ItemBuilder(item).onInteract(event -> event.setCancelled(true)).build() : item);

**Comment by Minemobs** [comment]
The setCancelled(true) only works when the item is used (right click/left click).
What you have to do instead is to use the method InventoryBuilder#setCancelled.
